"""Reusable domain and orchestration core for image2outfit."""

from .domain import (
    BodyRegion,
    ConstructionRole,
    FitProfile,
    GarmentLocation,
    GarmentPart,
    GarmentPartKind,
    GarmentSpecification,
    Laterality,
    LayerPosition,
    MaterialBehavior,
    PatternDart,
    PatternEdge,
    PatternEdgeRole,
    PatternPiece,
    Stitch,
    StitchEdge,
    SurfaceOrientation,
)
from .execution import (
    StageExecutionBinding,
    StageResultRequirement,
    expand_command_template,
    validate_stage_result,
)
from .pipeline import (
    PIPELINE_STAGES,
    ExecutionMode,
    PipelineStage,
    new_pipeline_state,
    next_pipeline_stage,
    resume_pipeline_state,
    run_pipeline,
    validate_pipeline_state,
)

__all__ = [
    "BodyRegion",
    "ConstructionRole",
    "ExecutionMode",
    "FitProfile",
    "GarmentLocation",
    "GarmentPart",
    "GarmentPartKind",
    "GarmentSpecification",
    "Laterality",
    "LayerPosition",
    "MaterialBehavior",
    "PatternDart",
    "PatternEdge",
    "PatternEdgeRole",
    "PatternPiece",
    "PIPELINE_STAGES",
    "PipelineStage",
    "StageExecutionBinding",
    "StageResultRequirement",
    "Stitch",
    "StitchEdge",
    "SurfaceOrientation",
    "expand_command_template",
    "new_pipeline_state",
    "next_pipeline_stage",
    "resume_pipeline_state",
    "run_pipeline",
    "validate_pipeline_state",
    "validate_stage_result",
]
