"""Reusable domain and orchestration core for image2outfit."""

from .domain import (
    BodyRegion,
    ConstructionRole,
    FitProfile,
    GarmentLocation,
    GarmentPart,
    GarmentPartKind,
    GarmentSpecification,
    Laterality,
    LayerPosition,
    MaterialBehavior,
    PatternDart,
    PatternEdge,
    PatternEdgeRole,
    PatternPiece,
    Stitch,
    StitchEdge,
    SurfaceOrientation,
)
from .execution import (
    StageExecutionBinding,
    StageResultRequirement,
    expand_command_template,
    validate_stage_result,
)
from .garment_spec import (
    CoordinateSystem,
    EvidenceRef,
    GarmentSpec,
    ProvenanceSpec,
    SpecSection,
    UnitSystem,
)
from .pipeline import (
    PIPELINE_STAGES,
    ExecutionMode,
    PipelineStage,
    new_pipeline_state,
    run_pipeline,
)
from .artifact_dag import (
    ArtifactKind,
    ArtifactRef,
    GarmentSectionName,
    PipelineArtifactDAG,
    StageContract,
)
from .artifact_bridge import artifact_ref_from_stage_result

__all__ = [
    "ArtifactKind",
    "ArtifactRef",
    "BodyRegion",
    "ConstructionRole",
    "CoordinateSystem",
    "EvidenceRef",
    "ExecutionMode",
    "FitProfile",
    "GarmentLocation",
    "GarmentPart",
    "GarmentPartKind",
    "GarmentSectionName",
    "GarmentSpec",
    "GarmentSpecification",
    "Laterality",
    "LayerPosition",
    "MaterialBehavior",
    "PatternDart",
    "PatternEdge",
    "PatternEdgeRole",
    "PatternPiece",
    "PIPELINE_STAGES",
    "PipelineArtifactDAG",
    "PipelineStage",
    "ProvenanceSpec",
    "SpecSection",
    "StageContract",
    "StageExecutionBinding",
    "StageResultRequirement",
    "Stitch",
    "StitchEdge",
    "SurfaceOrientation",
    "UnitSystem",
    "artifact_ref_from_stage_result",
    "expand_command_template",
    "new_pipeline_state",
    "run_pipeline",
    "validate_stage_result",
]
