#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PRERELEASE = re.compile(
    r"(?:^|[.\-])(alpha|beta|rc|pre|preview)(?:[.\-]|\d|$)", re.IGNORECASE
)


def read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return {}


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as stream:
        json.dump(value, stream, ensure_ascii=False, indent=2)
        stream.write("\n")
        temporary = Path(stream.name)
    temporary.replace(path)


def project_unity_version(root: Path) -> str:
    project_version = root / "ProjectSettings" / "ProjectVersion.txt"
    try:
        for line in project_version.read_text(encoding="utf-8-sig").splitlines():
            if line.startswith("m_EditorVersion:"):
                return line.split(":", 1)[1].strip()
    except OSError:
        pass
    return ""


def audit(root: Path = ROOT, require_unity_lock: bool = False) -> dict[str, Any]:
    lock_path = root / "config" / "toolchain-lock.json"
    manifest_path = root / "Packages" / "vpm-manifest.json"
    upm_lock_path = root / "Packages" / "packages-lock.json"
    lock = read_json(lock_path)
    manifest = read_json(manifest_path)
    errors: list[str] = []
    warnings: list[str] = []

    if lock.get("schemaVersion") != 1:
        errors.append("config/toolchain-lock.json must use schemaVersion 1")
    if lock.get("stableOnly") is not True:
        errors.append("stableOnly must be true")

    expected_unity = lock.get("unity", {}).get("version")
    actual_unity = project_unity_version(root)
    if not expected_unity or actual_unity != expected_unity:
        errors.append(
            f"Unity version mismatch: expected {expected_unity}, found {actual_unity or 'missing'}"
        )

    dependencies = manifest.get("dependencies", {})
    locked = manifest.get("locked", {})
    package_results: dict[str, Any] = {}
    for package_id, package in lock.get("vpmPackages", {}).items():
        expected = package.get("version")
        dependency_version = dependencies.get(package_id, {}).get("version")
        locked_version = locked.get(package_id, {}).get("version")
        passed = (
            bool(expected)
            and dependency_version == expected
            and locked_version == expected
        )
        package_results[package_id] = {
            "expected": expected,
            "dependency": dependency_version,
            "locked": locked_version,
            "passed": passed,
        }
        if not passed:
            errors.append(
                f"VPM package mismatch: {package_id} expected {expected}, "
                f"dependency={dependency_version}, locked={locked_version}"
            )
        if lock.get("stableOnly") is True and expected and PRERELEASE.search(expected):
            errors.append(f"prerelease package forbidden: {package_id}@{expected}")
        for field in ("source", "repository"):
            value = package.get(field)
            if value is not None and not str(value).startswith("https://"):
                errors.append(f"{package_id} {field} must use https")

    for package_id, expected_dependencies in lock.get(
        "dependencyContracts", {}
    ).items():
        actual_dependencies = locked.get(package_id, {}).get("dependencies", {})
        for dependency_id, expected_range in expected_dependencies.items():
            actual_range = actual_dependencies.get(dependency_id)
            if actual_range != expected_range:
                errors.append(
                    f"VPM dependency contract mismatch: {package_id} -> {dependency_id} "
                    f"expected {expected_range}, found {actual_range or 'missing'}"
                )

    blender_version = str(lock.get("blender", {}).get("version", ""))
    if not re.fullmatch(r"4\.4\.\d+", blender_version):
        errors.append(
            f"Blender must be pinned to an exact 4.4 patch, found {blender_version or 'missing'}"
        )

    unity_lock_present = upm_lock_path.is_file()
    if require_unity_lock and not unity_lock_present:
        errors.append(
            "Packages/packages-lock.json was not generated by Unity Package Manager"
        )
    elif not unity_lock_present:
        warnings.append(
            "Packages/packages-lock.json will be required after Unity resolves the project"
        )

    return {
        "schemaVersion": 1,
        "checkedAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "passed": not errors,
        "stableOnly": lock.get("stableOnly") is True,
        "unity": {"expected": expected_unity, "project": actual_unity},
        "blender": {"expected": blender_version},
        "packages": package_results,
        "unityPackageLockPresent": unity_lock_present,
        "errors": errors,
        "warnings": warnings,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Audit the reproducible IMAGE2OUTFIT toolchain lock"
    )
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--require-unity-lock", action="store_true")
    args = parser.parse_args()
    result = audit(args.root.resolve(), args.require_unity_lock)
    if args.output:
        output = args.output if args.output.is_absolute() else args.root / args.output
        write_json(output.resolve(), result)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["passed"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
